apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: copy-pipeline
spec:
  params:
    - description: Source Repository URL
      name: git-url
      type: string
    - default: ""
      description: Revision of the Source Repository
      name: revision
      type: string
    - description: Fully Qualified Output Image
      name: output-image
      type: string
    - default: ""
      description: Build dependencies to be prefetched by Cachi2
      name: prefetch-input
      type: string
    - default: ""
      description: Image tag expiration time, time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively.
      name: image-expires-after
  results:
    - description: ""
      name: IMAGE_URL
      value: $(tasks.oci-copy.results.IMAGE_URL)
    - description: ""
      name: IMAGE_DIGEST
      value: $(tasks.oci-copy.results.IMAGE_DIGEST)
    - description: ""
      name: CHAINS-GIT_URL
      value: $(tasks.clone-repository.results.url)
    - description: ""
      name: CHAINS-GIT_COMMIT
      value: $(tasks.clone-repository.results.commit)
  tasks:
    - name: init
      params:
        - name: image-url
          value: $(params.output-image)
        - name: rebuild
          value: $(params.rebuild)
        - name: skip-checks
          value: $(params.skip-checks)
      taskRef:
        params:
          - name: name
            value: init
          - name: bundle
            value: quay.io/redhat-appstudio-tekton-catalog/task-init:0.2@sha256:61f1202766cd66242c8472b16aa7fa1a20f8d9a5d674cbad27ffd4b3d067e936
          - name: kind
            value: task
        resolver: bundles
    - name: clone-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.revision)
      runAfter:
        - init
      taskRef:
        params:
          - name: name
            value: git-clone
          - name: bundle
            value: quay.io/redhat-appstudio-tekton-catalog/task-git-clone:0.1@sha256:e1f7a275d722bc3147a65fcd772b16b54ccb6ce81c76939bc1052b2438dd2ccf
          - name: kind
            value: task
        resolver: bundles
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"
      workspaces:
        - name: output
          workspace: workspace
        - name: basic-auth
          workspace: git-auth
    - name: oci-copy
      params:
        - name: IMAGE
          value: $(params.output-image)
        - name: OCI_COPY_FILE
          value: $(params.oci_copy_file)
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)
        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)
      runAfter:
        - clone-repository
      taskRef:
        params:
          - name: name
            value: oci-copy
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-oci-copy:0.1@sha256:dbedac36bcef28d60a2b8482c78161e643fd8edc4b65e72e867c22229ad9a400
          - name: kind
            value: task
        resolver: bundles
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"
      workspaces:
        - name: source
          workspace: workspace
    - name: apply-tags
      params:
        - name: IMAGE
          value: $(tasks.oci-copy.results.IMAGE_URL)
      runAfter:
        - oci-copy
      taskRef:
        params:
          - name: name
            value: apply-tags
          - name: bundle
            value: quay.io/redhat-appstudio-tekton-catalog/task-apply-tags:0.1@sha256:7cf2482a7f50a4c493af0604ff388ff5cc2e2579cb3bf889cfa2587c723aa312
          - name: kind
            value: task
        resolver: bundles
  workspaces:
    - name: workspace
    - name: git-auth
      optional: true
