apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/ralphbean/merlinite-poc?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: models
    appstudio.openshift.io/component: merlinite-poc
    pipelines.appstudio.openshift.io/type: build
  name: merlinite-poc-on-push
  namespace: rhel-ai-poc-tenant
spec:
  params:
    - name: oci_copy_file
      value: oci-copy.yaml
    - name: git-url
      value: '{{source_url}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/rhel-ai-poc-tenant/models/merlinite-poc:{{revision}}
    - name: revision
      value: '{{revision}}'
  pipelineRef:
    name: copy-pipeline
  taskRunTemplate: {}
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
        status: {}
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
